In [27]:
import numpy as np
import pandas as pd

In [28]:
data1 = pd.read_csv("E:/AI_ML_Learning/data/penguins_size.csv")
print("Data set shape: ", data1.shape)
display(data1.head())

Data set shape:  (344, 7)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [4]:
print("column names", data1.columns.tolist())

column names ['species', 'island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex']

In [5]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [7]:
print(data1.isnull().sum())

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [8]:
print(data1.duplicated().sum())

0

In [9]:
print(data1.describe(include="all"))

       species  island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
count      344     344        342.000000       342.000000         342.000000
unique       3       3               NaN              NaN                NaN
top     Adelie  Biscoe               NaN              NaN                NaN
freq       152     168               NaN              NaN                NaN
mean       NaN     NaN         43.921930        17.151170         200.915205
std        NaN     NaN          5.459584         1.974793          14.061714
min        NaN     NaN         32.100000        13.100000         172.000000
25%        NaN     NaN         39.225000        15.600000         190.000000
50%        NaN     NaN         44.450000        17.300000         197.000000
75%        NaN     NaN         48.500000        18.700000         213.000000
max        NaN     NaN         59.600000        21.500000         231.000000

        body_mass_g   sex
count    342.000000   334
unique          NaN     3
top             NaN  MALE
freq            NaN   168
mean    4201.754386   NaN
std      801.954536   NaN
min     2700.000000   NaN
25%     3550.000000   NaN
50%     4050.000000   NaN
75%     4750.000000   NaN
max     6300.000000   NaN

In [10]:
def clean_column_names(data):
    data = data.copy()
    data.columns = data.columns.str.strip()
    return data

In [12]:
def fill_missing_values(data):
    data = data.copy()
    numeric_columns = data.select_dtypes(include=np.number).columns
    for column in numeric_columns:
        data[column] = data[column].fillna(data[column].median())
    
    categorical_columns = data.select_dtypes(
        include=["object", "category"]
    ).columns
    for column in categorical_columns:
        if data[column].isnull().any():
            if not data[column].mode().empty:
                data[column] = data[column].fillna(data[column].mode()[0])
            else:
                data[column] = data[column].fillna("Unknown")
    return data

In [13]:
cleaned_data = clean_column_names(data1)
cleaned_data = fill_missing_values(cleaned_data)

C:\Users\User_PC\AppData\Local\Temp\ipykernel_13524\1004962745.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = data.select_dtypes(

In [14]:
print(cleaned_data.isnull().sum())

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [16]:
print(cleaned_data.duplicated().sum())

0

In [17]:
display(cleaned_data.head())

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,MALE
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,FEMALE

In [18]:
display(cleaned_data.tail())

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,44.45,17.3,197.0,4050.0,MALE
340,Gentoo,Biscoe,46.80,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.40,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.20,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.90,16.1,213.0,5400.0,MALE

In [19]:
numeric_data = cleaned_data.select_dtypes(include=np.number)
numbers = numeric_data.to_numpy(dtype= float)

In [20]:
print ("numerical columns:", numeric_data.columns.tolist())

numerical columns: ['culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g']

In [23]:
print("Mean:")
print(np.nanmean(numbers, axis= 0))
print("Median:")
print(np.nanmedian(numbers, axis = 0))
print("minimum:")
print(np.nanmin(numbers, axis = 0))
print("maximum:")
print(np.nanmax(numbers, axis = 0))

Mean:
[  43.925        17.15203488  200.89244186 4200.87209302]
Median:
[  44.45   17.3   197.   4050.  ]
minimum:
[  32.1   13.1  172.  2700. ]
maximum:
[  59.6   21.5  231.  6300. ]

In [24]:
print("Range:")
print(np.nanmax(numbers, axis = 0)- np.nanmin(numbers, axis = 0))
print("Standard Deviation:")
print(np.nanstd(numbers, axis = 0))

Range:
[  27.5    8.4   59.  3600. ]
Standard Deviation:
[  5.43587352   1.96619584  14.00342777 798.53333647]

In [25]:
cleaned_data.to_csv(
    "E:/AI_ML_Learning/data/penguins_cleaned.csv",
    index = False
)
print("cleaned dataset saved successfully.")

cleaned dataset saved successfully.

In [26]:
verified_data = pd.read_csv("E:/AI_ML_Learning/data/penguins_cleaned.csv")
print("Shape:", verified_data.shape)
print("missing Value: ", verified_data.isnull().sum())
print("Duplicat rows: ", verified_data.duplicated().sum())
display(verified_data.head())

Shape: (344, 7)
missing Value:  species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64
Duplicat rows:  0

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,MALE
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,FEMALE